[theme]
base = "light"
primaryColor = "#1a73e8"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#172b4d"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false